# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
        java-package: jdk
        cache: 'maven'
        server-id: central
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: spotbugs
      run: mvn -B verify spotbugs:spotbugs --file pom.xml
    - uses: jwgmeligmeyling/spotbugs-github-action@master
      with:
        path: '**/spotbugsXml.xml'
    - name: Publish snapshot to OSS
      if: ${{ github.ref == 'refs/heads/master' }}
      run: mvn --batch-mode deploy --file pom.xml -s central-settings.xml
      env:
        CENTRAL_TOKEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
        CENTRAL_TOKEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
